# Generated by Django 5.1.2 on 2024-10-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='image1',
            field=models.ImageField(default=1, upload_to='product_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='image2',
            field=models.ImageField(default=1, upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
