# Generated by Django 5.1.2 on 2024-10-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_workshop_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_description', models.TextField()),
                ('blog_content', models.TextField()),
                ('blog_date', models.DateField()),
                ('blogger_name', models.CharField(max_length=100)),
                ('blog_image', models.ImageField(upload_to='product_images/')),
            ],
        ),
    ]
