# Generated by Django 5.1.2 on 2024-10-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
