# Generated by Django 4.2.6 on 2024-12-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='image3',
            field=models.ImageField(default='default_image.jpg', upload_to='product_images/'),
        ),
    ]
